### ISSUE TITLE
Scan tab not refreshed while switching between tabs

### ISSUE THREAD

**Issue by fdechelle** [armadito/armadito-av#6]
Armadito 0.10.0 installed on windows 7.

After a scan is started, you can switch between tabs but tabs are not updated immediately. For example, while coming back on scan tab while Armadito is scanning a really big file shows 0/0/0 on scanned/found/suspect numbers until the current file is scanned. Also the last threat found text is removed even if the found count is right after such a switch.

I expect at least to see the same stuffs I had before the tab switch.

I guess the last known tab state should be saved between switchs.

**Comment by vhamon** [comment]
This needs a refactoring in gui, using angular services or factories
http://stackoverflow.com/questions/33265783/how-to-persist-data-and-model-in-angular-js
http://stackoverflow.com/questions/21919962/share-data-between-angularjs-controllers
https://docs.angularjs.org/guide/service
http://blog.thoughtram.io/angular/2015/07/07/service-vs-factory-once-and-for-all.html
